import { z } from "zod";

export const documentSummarySchema = z.object({
  title: z.string().min(1).max(160),
  shortSummary: z.string().min(1).max(220),
  detailedSummary: z.string().min(1).max(1400),
  evidenceValue: z.string().min(1).max(520),
  recommendedUse: z.string().min(1).max(420),
  documentType: z.string().min(1).max(80),
  confidence: z.number().int().min(0).max(100),
  primaryDate: z.string().min(1).max(32).nullable(),
  primaryDateReason: z.string().min(1).max(180),
  notableFacts: z.array(z.string().min(1).max(220)).max(8),
  people: z.array(z.string().min(1).max(120)).max(10),
  organizations: z.array(z.string().min(1).max(160)).max(10),
  dates: z.array(z.string().min(1).max(120)).max(10),
  locations: z.array(z.string().min(1).max(120)).max(10),
  tags: z.array(z.string().min(1).max(48)).max(12),
  possibleCriteria: z.array(z.string().min(1).max(80)).max(6),
  missingContext: z.array(z.string().min(1).max(180)).max(6),
  riskFlags: z.array(z.string().min(1).max(180)).max(6),
});

export const documentSummaryJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "shortSummary",
    "detailedSummary",
    "evidenceValue",
    "recommendedUse",
    "documentType",
    "confidence",
    "primaryDate",
    "primaryDateReason",
    "notableFacts",
    "people",
    "organizations",
    "dates",
    "locations",
    "tags",
    "possibleCriteria",
    "missingContext",
    "riskFlags",
  ],
  properties: {
    title: { type: "string" },
    shortSummary: { type: "string" },
    detailedSummary: { type: "string" },
    evidenceValue: { type: "string" },
    recommendedUse: { type: "string" },
    documentType: { type: "string" },
    confidence: { type: "integer", minimum: 0, maximum: 100 },
    primaryDate: {
      type: ["string", "null"],
    },
    primaryDateReason: { type: "string" },
    notableFacts: {
      type: "array",
      items: { type: "string" },
      maxItems: 8,
    },
    people: {
      type: "array",
      items: { type: "string" },
      maxItems: 10,
    },
    organizations: {
      type: "array",
      items: { type: "string" },
      maxItems: 10,
    },
    dates: {
      type: "array",
      items: { type: "string" },
      maxItems: 10,
    },
    locations: {
      type: "array",
      items: { type: "string" },
      maxItems: 10,
    },
    tags: {
      type: "array",
      items: { type: "string" },
      maxItems: 12,
    },
    possibleCriteria: {
      type: "array",
      items: { type: "string" },
      maxItems: 6,
    },
    missingContext: {
      type: "array",
      items: { type: "string" },
      maxItems: 6,
    },
    riskFlags: {
      type: "array",
      items: { type: "string" },
      maxItems: 6,
    },
  },
} as const;
